server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:localhost}:3306/del_parque
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}